[tool.pymend]
extend-exclude             = "docs/|tests/"
output-style               = "google"
input-style                = "google"
force-params-min-n-params  = 2
force-meta-min-func-length = 5
check                      = true

[tool.ruff]
# Enable pycodestyle (`E`) and Pyflakes (`F`) codes by default.
select = ["ALL"]
ignore = ["ANN101", "ANN401", "TRY003", "TRY300", "COM", "FA100", "PTH"]

# Exclude a variety of commonly ignored directories.
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".hg",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "venv",
    "docs",
]

# Same as Black.
line-length = 88

# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

# Assume Python 3.11.
target-version = "py311"

[tool.black]
line-length    = 88
target-version = ['py311']

[tool.ruff.per-file-ignores]
"__init__.py"       = ["E402", "F401"]
"tests/test_*.py"   = ["ANN201", "S101", "SLF001", "PLR2004"]
"setup.py"          = ["D100"]
"flask_app/user.py" = ["UP007"]

[tool.ruff.pydocstyle]
convention = "google" # Accepts: "google", "numpy", or "pep257".

[tool.ruff.pylint]
max-args = 15

[tool.pyright]
include                            = ["flask_app"]
exclude                            = ["tests"]
pythonVersion                      = "3.11"
strictListInference                = true
strictDictionaryInference          = true
reportPropertyTypeMismatch         = "error"
reportFunctionMemberAccess         = "error"
reportMissingTypeStubs             = "none"
reportUntypedFunctionDecorator     = "error"
reportUntypedClassDecorator        = "error"
reportUntypedBaseClass             = "error"
reportUntypedNamedTuple            = "error"
reportPrivateUsage                 = "error"
reportConstantRedefinition         = "error"
reportOverlappingOverload          = "error"
reportMissingParameterType         = "error"
reportUnnecessaryIsInstance        = "error"
reportUnnecessaryCast              = "error"
reportUnnecessaryComparison        = "error"
reportUnnecessaryContains          = "error"
reportAssertAlwaysTrue             = "error"
reportUnnecessaryTypeIgnoreComment = "error"
reportImplicitOverride             = "none"
reportShadowedImports              = "error"

[tool.pylint.basic]
# Good variable names which should always be accepted, separated by a comma.
good-names = ["i", "j", "k", "ex", "Run", "_", "x", "y", "z", "e"]

[tool.pylint.design]
# Maximum number of arguments for function / method.
max-args = 15

# Maximum number of attributes for a class (see R0902).
max-attributes = 7

[tool.coverage.run]
branch = true
source = ["flask_app"]

[tool.pytest.ini_options]
testpaths = ["tests"]
