# This workflow will run the tests on the FlaskApp repo

name: build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Checkout app library
        uses: actions/checkout@v5
      - name: Installation
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r tests/requirements.txt

      - name: Lint with ruff
        uses: chartboost/ruff-action@v1
        with:
          version: 0.6.9
      - name: Check formatting with ruff
        uses: chartboost/ruff-action@v1
        with:
          version: 0.6.9
          args: format

      - name: Typecheck with pyright
        uses: jakebailey/pyright-action@v2
        with:
          version: 1.1.383

      - name: Thorough check with pylint
        run: pylint flask_app
      - name: Test with pytest
        env:
          AWS_TESTDB_ACCESS_KEY_ID: ${{ secrets.AWS_TESTDB_ACCESS_KEY_ID }}
          AWS_TESTDB_SECRET_ACCESS_KEY: ${{ secrets.AWS_TESTDB_SECRET_ACCESS_KEY }}
        run: |
          coverage run -m pytest --durations=10
          coverage report -m
          coverage json
          coverage html
      - name: Archive code coverage results
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage-report
          path: htmlcov/
